# Generated by Django 5.2.14 on 2026-05-10 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milkpurchase',
            old_name='notes',
            new_name='anotacoes',
        ),
        migrations.RenameField(
            model_name='milkpurchase',
            old_name='created_at',
            new_name='criadoEm',
        ),
        migrations.RenameField(
            model_name='milkpurchase',
            old_name='date',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='milkpurchase',
            old_name='liters',
            new_name='litros',
        ),
        migrations.RenameField(
            model_name='milkpurchase',
            old_name='price_per_liter',
            new_name='precoPorLitro',
        ),
        migrations.RenameField(
            model_name='milkpurchase',
            old_name='total_price',
            new_name='totalPreco',
        ),
    ]
