# Generated by Django 5.2.14 on 2026-05-10 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_purchases', '0002_rename_notes_milkpurchase_anotacoes_and_more'),
        ('suppliers', '0002_rename_notes_supplier_anotacoes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milkpurchase',
            options={'verbose_name': 'Compra de Leite', 'verbose_name_plural': 'Compras de Leite'},
        ),
        migrations.RemoveField(
            model_name='milkpurchase',
            name='supplier',
        ),
        migrations.AddField(
            model_name='milkpurchase',
            name='fornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compras_leite', to='suppliers.supplier'),
            preserve_default=False,
        ),
    ]
