# Generated by Django 5.2.14 on 2026-05-10 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='notes',
            new_name='anotacoes',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='city',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='created_at',
            new_name='criadoEm',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='address',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='phone',
            new_name='telefone',
        ),
    ]
