# Generated by Django 5.2.14 on 2026-05-10 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_purchases', '0003_alter_milkpurchase_options_and_more'),
        ('suppliers', '0002_rename_notes_supplier_anotacoes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplier',
            new_name='Fornecedor',
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
